export const SUPPORTER_TIER_1_ROLE_ID = Bun.env.SUPPORTER_TIER_1_ROLE_ID;
export const SUPPORTER_TIER_2_ROLE_ID = Bun.env.SUPPORTER_TIER_2_ROLE_ID;
export const SUPPORTER_TIER_3_ROLE_ID = Bun.env.SUPPORTER_TIER_3_ROLE_ID;
